name: tasky
description: "A TODO app project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0-236.0.dev <4.0.0'

dependencies:
  dio: ^5.4.3+1
  either_dart: ^1.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.1
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  google_fonts: ^6.2.1
  json_annotation: ^4.9.0
  lazy_load_scrollview: ^1.3.0
  flutter_screenutil: ^5.9.1
  intl_phone_field: ^3.2.0
  auto_size_text: ^3.0.0
  intl: ^0.19.0
  dotted_decoration: ^2.0.0
  dropdown_button2: ^2.3.9
  image_picker: ^1.1.2
  http_parser: ^4.0.2
  retrofit: ^4.1.0
  pretty_qr_code: ^3.3.0
  connectivity_plus: ^6.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_platform_widgets: ^7.0.0
  path_provider: ^2.1.3
  pretty_dio_logger: ^1.3.1
  json_serializable: ^6.8.0
  freezed: ^2.5.3
  change_app_package_name: ^1.2.0
  flutter_launcher_icons: ^0.13.0
  flutter_native_splash: ^2.4.0
  hive_generator:
  mobile_scanner: ^5.1.1
#  to set the size of the app on windows
  window_manager: ^0.3.9
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  retrofit_generator: ^8.0.6
  build_runner: any


flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/images/onboarding_arrow.png
  - assets/images/tasky_logo.png
  - assets/images/logo_12.png
